import { Product, FoodPairing, SocialPost, Retailer } from './types';

export const BRAND_NAME = "AJÍ VENENO";
export const BRAND_TAGLINE = "Hecho pa' picar";

export const PRODUCTS: Product[] = [
  {
    id: 'pebre',
    name: 'PEBRE',
    tagline: 'Ají verde americano y tomate deshidratado.',
    spiceLevel: 2,
    spiceText: 'Picor 2/5 • Ají Verde Americano & Tomate Deshidratado',
    description: 'Elaborada con ají verde americano seleccionado y tomate deshidratado al sol, que aporta una acidez noble y un dulzor concentrado. Picor fresco, amable y equilibrado para acompañar sin saturar el paladar.',
    tasteNotes: ['Ají verde americano', 'Tomate deshidratado al sol', 'Cilantro fresco de huerto', 'Sal de Cáhuil'],
    pairing: 'Choripán gourmet en masa madre, empanadas de pino al horno, tiraditos de corvina austral, sopaipillas campesinas y pastel de choclo.',
    volume: '165 g',
    price: '$4.990 CLP',
    badge: 'PICOR 2/5',
    image: '/pebre.png',
    bgColor: '#397A3C',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  },
  {
    id: 'cacho',
    name: 'CACHO',
    tagline: 'Ají cacho de cabra ahumado.',
    spiceLevel: 3,
    spiceText: 'Picor 3/5 • Cacho de Cabra Ahumado',
    description: 'Auténtico ají cacho de cabra del sur de Chile, ahumado lentamente con leña de roble nativo en zarandas tradicionales. Notas tostadas profundas, calidez envolvente y un picor tradicional perfectamente equilibrado.',
    tasteNotes: ['Cacho de cabra ahumado', 'Humo de leña nativa', 'Merkén de guarda', 'Toque de ajo asado'],
    pairing: 'Costillar de cerdo glaseado, smash burgers de entraña en brioche, arrollado huaso y quesos madurados.',
    volume: '135 cc',
    price: '$5.290 CLP',
    badge: 'PICOR 3/5',
    image: '/cacho.png',
    bgColor: '#C25E00',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  },
  {
    id: 'chileno',
    name: 'CHILENO',
    tagline: 'Salsa de ají verde chileno.',
    spiceLevel: 4,
    spiceText: 'Picor 4/5 • Salsa de Ají Verde Chileno',
    description: 'Pura potencia criolla. Salsa de ají verde chileno cosechado en su punto máximo de pungencia, vinagre de manzana orgánica de Chiloé y cristales de sal. Picor vibrante, punzante y con carácter patrio para cortes parrilleros.',
    tasteNotes: ['Ají verde chileno puro', 'Pungencia criolla vibrante', 'Vinagre de manzana Chiloé', 'Ajo chilote al rescoldo'],
    pairing: 'Plateada al Carménère, entraña angus a la brasa, sándwich en marraqueta crujiente y anticuchos.',
    volume: '165 g',
    price: '$5.490 CLP',
    badge: 'PICOR 4/5',
    image: '/chileno.png',
    bgColor: '#1F5E2B',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  },
  {
    id: 'fuego',
    name: 'FUEGO',
    tagline: 'Pichún de mono, ajó de pájaro y habanero.',
    spiceLevel: 5,
    spiceText: 'Picor 5/5 • Pichún de Mono, Ajó de Pájaro & Habanero',
    description: 'Nuestra receta de máxima combustión: una poderosa combinación de ají pichún de mono, ají ajó de pájaro y ají habanero. Picor volcánico, combustión inmediata y sudor garantizado para los verdaderos fanáticos del calor extremo.',
    tasteNotes: ['Ají pichún de mono', 'Ají ajó de pájaro', 'Ají habanero', 'Persistencia volcánica'],
    pairing: 'Tomahawk a las brasas de espino, bife de chorizo madurado, cordero al palo, tacos de lechón confitado y ostras gratinadas.',
    volume: '165 g',
    price: '$5.990 CLP',
    badge: 'PICOR 5/5 • EXTREMO',
    image: '/fuego.png',
    bgColor: '#111111',
    accentColor: '#D92323',
    textColor: '#FFF9EE',
    borderColor: '#F4C430',
  }
];

export const MILD_PRODUCTS: Product[] = [
  {
    id: 'pime',
    name: 'PIME',
    tagline: 'Pimentón al humo.',
    spiceLevel: 0,
    spiceText: '0% Picor • Pimentón al Humo',
    description: 'Pimentones rojos dulces asados lentamente sobre leña nativa al humo continuo, reducción de tomate maduro y aceite de oliva virgen extra. Perfil profundamente ahumado, dulce y sin picor.',
    tasteNotes: ['Pimentón dulce al humo', 'Ahumado a leña nativa', 'Aceite de oliva virgen', 'Sal de mar de Cáhuil'],
    pairing: 'Choripán gourmet de longaniza artesanal en masa madre, carpaccio de res, verduras a la parrilla y pescados a la sal.',
    volume: '145 g',
    price: '$4.990 CLP',
    badge: 'PIMENTÓN AL HUMO',
    image: '/pime.png',
    bgColor: '#C84B31',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  },
  {
    id: 'chilote',
    name: 'CHILOTE',
    tagline: 'Salsa de ajo chilote.',
    spiceLevel: 0,
    spiceText: '0% Picor • Salsa de Ajo Chilote',
    description: 'Auténtica salsa de ajo chilote elaborada con cabezas enteras asadas pacientemente al rescoldo de encina, emulsionadas en frío con aceite de oliva virgen extra del Valle del Huasco y gotas de limón de Pica.',
    tasteNotes: ['Ajo chilote al rescoldo', 'Emulsión cremosa', 'Aceite virgen Huasco', 'Toque limón de Pica'],
    pairing: 'Bife angus madurado, mollejas glaseadas al limón, entraña a las brasas, papas rústicas y sándwiches gourmet.',
    volume: '145 g',
    price: '$5.290 CLP',
    badge: 'AJO CHILOTE',
    image: '/chilote.png',
    bgColor: '#D99B26',
    accentColor: '#111111',
    textColor: '#111111',
    borderColor: '#111111',
  },
  {
    id: 'berenja',
    name: 'BERENJA',
    tagline: 'Berenjena al humo.',
    spiceLevel: 0,
    spiceText: '0% Picor • Berenjena al Humo',
    description: 'Berenjenas asadas enteras al humo de carbón vegetal hasta obtener una textura untuosa y un marcado bouquet ahumado, infusionadas con aceite de oliva virgen, comino tostado y especias suaves.',
    tasteNotes: ['Berenjena al humo directo', 'Carbón vegetal noble', 'Aceite de oliva virgen', 'Comino tostado suave'],
    pairing: 'Cordero al palo, tablas de charcutería artesanal, quesos de oveja madurados y tostadas de masa madre.',
    volume: '145 g',
    price: '$5.290 CLP',
    badge: 'BERENJENA AL HUMO',
    image: '/berenja.png',
    bgColor: '#4A2B4B',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  },
  {
    id: 'seta',
    name: 'SETA',
    tagline: 'Salsa de champiñón portobello al humo.',
    spiceLevel: 0,
    spiceText: '0% Picor • Portobello al Humo',
    description: 'Hongos portobello frescos sellados y ahumados a la leña, emulsionados con reducción de manteca de campo, vino blanco criollo, tomillo y hierbas silvestres. Gran potencia umami y humo elegante.',
    tasteNotes: ['Portobello al humo de leña', 'Concentrado umami', 'Vino blanco Casablanca', 'Tomillo silvestre'],
    pairing: 'Bife de chorizo, pastas caseras, risottos campesinos, mollejas crocantes y cortes nobles a la brasa.',
    volume: '145 g',
    price: '$5.490 CLP',
    badge: 'PORTOBELLO AL HUMO',
    image: '/seta.png',
    bgColor: '#594031',
    accentColor: '#F4C430',
    textColor: '#FFF9EE',
    borderColor: '#111111',
  }
];

export const SPICE_LEVELS = [
  {
    level: 1,
    id: 'suave-intro',
    title: 'PARTE TRANQUILO',
    subtitle: 'Cosquilleo cordial y fresco',
    description: 'Notas herbales y cítricas que despiertan el paladar sin invadir. La entrada perfecta al universo de Ají Veneno.',
    heatRating: '20%',
    flames: 1,
    warning: 'Para quienes buscan sabor y aroma fresco antes que picor fuerte.',
    antidote: 'Un sorbo de Sauvignon Blanc o un bocado de palta Hass.',
    suggestedSauce: 'PEBRE (Picor 2/5 • Ají Verde Americano & Tomate Deshidratado)',
    bgIntensity: 'from-[#F4EBD8] to-[#FFF9EE]',
    accentBadge: 'bg-[#397A3C] text-white',
  },
  {
    level: 2,
    id: 'pebre',
    title: 'PEBRE',
    subtitle: 'Ají verde americano & tomate deshidratado',
    description: 'Picor fresco y equilibrado (Nivel 2) con la acidez noble y el dulzor concentrado del tomate deshidratado al sol.',
    heatRating: '40%',
    flames: 2,
    warning: 'Perfecto para choripanes gourmet, ceviches y empanadas tradicionales.',
    antidote: 'Copa de vino blanco frío o miga de pan amasado.',
    suggestedSauce: 'PEBRE (Picor 2/5 • Ají Verde Americano)',
    bgIntensity: 'from-[#F4C430] to-[#E5B520]',
    accentBadge: 'bg-[#111111] text-[#F4C430]',
  },
  {
    level: 3,
    id: 'cacho',
    title: 'CACHO',
    subtitle: 'Ají cacho de cabra ahumado a la leña',
    description: 'Picor medio tradicional (Nivel 3) con profundo aroma a leña nativa en zarandas del sur y merkén de guarda.',
    heatRating: '65%',
    flames: 3,
    warning: 'El estándar criollo para la parrilla, costillares y carnes al horno.',
    antidote: 'Trago de cerveza artesanal o vino Carménère reserva.',
    suggestedSauce: 'CACHO (Picor 3/5 • Cacho de Cabra Ahumado)',
    bgIntensity: 'from-[#E55026] to-[#D92323]',
    accentBadge: 'bg-[#F4C430] text-[#111111]',
  },
  {
    level: 4,
    id: 'chileno',
    title: 'CHILENO',
    subtitle: 'Salsa de ají verde chileno puro',
    description: 'Potencia sostenida (Nivel 4). Ají verde chileno cosechado en su punto máximo de pungencia para paladares curtidos.',
    heatRating: '85%',
    flames: 4,
    warning: 'Para comensales que exigen picor punzante, sudor y sabor auténticamente chileno.',
    antidote: 'Cucharada de miel de ulmo o pan con mantequilla de campo.',
    suggestedSauce: 'CHILENO (Picor 4/5 • Salsa de Ají Verde Chileno)',
    bgIntensity: 'from-[#D92323] to-[#A31212]',
    accentBadge: 'bg-[#111111] text-[#FFF9EE]',
  },
  {
    level: 5,
    id: 'fuego',
    title: 'FUEGO VOLCÁNICO',
    subtitle: 'Pichún de mono, ajó de pájaro y habanero',
    description: 'Máxima combustión (Nivel 5). Triple mezcla de ají pichún de mono, ají ajó de pájaro y habanero. Calor volcánico inmediato.',
    heatRating: '100%',
    flames: 5,
    warning: 'DOSIFICAR CON GOTERO. PICOR EXTREMO 5/5.',
    antidote: 'Leche entera fría, manjar de campo o respeto absoluto.',
    suggestedSauce: 'FUEGO (Picor 5/5 • Pichún, Pájaro & Habanero)',
    bgIntensity: 'from-[#930909] to-[#111111]',
    accentBadge: 'bg-[#F4C430] text-[#111111] animate-bounce',
  },
];

export const FOOD_PAIRINGS: FoodPairing[] = [
  {
    id: 'tiradito',
    name: 'TIRADITO DE CORVINA AUSTRAL',
    subtitle: 'Pesca Artesanal & Cítricos del Huasco',
    verdict: 'FRESCURA & PRECISIÓN',
    rating: '10 / 10',
    chiliApproved: true,
    imageAlt: 'Tiradito fino de corvina austral con leche de tigre y ají verde criollo',
    quote: 'Láminas finas de corvina fresca, rocío de limón de pica y gotas de PEBRE con tomate deshidratado para lograr ese balance fresco y amable.',
    tags: ['Corvina Austral', 'Limón de Pica', 'Tomate Deshidratado', 'Sal de Cáhuil'],
    sauceRecommendation: 'PEBRE (Picor 2/5 • Ají Verde Americano)',
  },
  {
    id: 'churrasco',
    name: 'SÁNDWICH DE ENTRAÑA & WAGYU',
    subtitle: 'Focaccia a la Leña & Palta Laminada',
    verdict: 'CORTE NOBLE ELEVADO',
    rating: '10 / 10',
    chiliApproved: true,
    imageAlt: 'Sándwich de entraña a las brasas en focaccia de masa madre con ají ahumado',
    quote: 'El jugo de la entraña sellada a fuego vivo se amalgama a la perfección con el picor punzante de CHILENO sobre pan tostado a la brasa.',
    tags: ['Entraña Angus / Wagyu', 'Focaccia Masa Madre', 'Ají Verde Chileno', 'Corteza Crocante'],
    sauceRecommendation: 'CHILENO (Picor 4/5)',
  },
  {
    id: 'empanada',
    name: 'EMPANADA DE PLATEADA AL CARMÉNÈRE',
    subtitle: 'Horno de Barro & Masa Criolla Crujiente',
    verdict: 'RECETA DE AUTOR',
    rating: '10 / 10',
    chiliApproved: true,
    imageAlt: 'Empanada criolla de plateada al vino Carménère con aceituna de Huasco y ají',
    quote: 'Plateada braseada durante 8 horas en reducción de vino chileno. Se abre una pequeña incisión y se vierte CACHO para fundir caldillo noble y humo de roble.',
    tags: ['Plateada 8h al Vino', 'Reducción Carménère', 'Cacho de Cabra', 'Cebolla Caramelizada'],
    sauceRecommendation: 'CACHO (Picor 3/5 • Cacho de Cabra Ahumado)',
  },
  {
    id: 'sopaipillas',
    name: 'SOPAIPILLAS DE ZAPALLO CAMOTE & PEBRE AUSTRAL',
    subtitle: 'Aceite de Oliva Huasco & Sal de Cáhuil',
    verdict: 'TRADICIÓN GOURMET',
    rating: '9.9 / 10',
    chiliApproved: true,
    imageAlt: 'Sopaipillas gourmet de zapallo camote con pebre de quínoa y ají verde',
    quote: 'Masa dorada elaborada con zapallo camote asado al rescoldo, pebre fresco de quínoa y una pincelada de PEBRE recién abierto.',
    tags: ['Zapallo Camote Asado', 'Tomate Deshidratado', 'Ají Verde Americano', 'Sal de Cáhuil'],
    sauceRecommendation: 'PEBRE (Picor 2/5)',
  },
  {
    id: 'asado',
    name: 'TOMAHAWK & ASADO DE TIRA PRIME',
    subtitle: 'Brasas de Leña de Espino & Sal Gruesa',
    verdict: 'MARIDAJE SUPREMO',
    rating: '10 / 10',
    chiliApproved: true,
    imageAlt: 'Tomahawk prime a las brasas de espino con ají ahumado con miel de ulmo',
    quote: 'Cortes nobles con generosa infiltración grasa. La combustión extrema de FUEGO (pichún de mono, ajó de pájaro y habanero) corta la grasa y eleva la carne.',
    tags: ['Tomahawk Prime', 'Pichún de Mono', 'Habanero', 'Carbón de Espino Vivo'],
    sauceRecommendation: 'FUEGO (Picor 5/5 • Fuego Extremo)',
  },
  {
    id: 'cereal',
    name: 'CEREAL INDUSTRIAL CON LECHE',
    subtitle: 'Para esto NO es el Ají Gourmet',
    verdict: 'SACRILEGIO GASTRONÓMICO',
    rating: '0 / 10',
    chiliApproved: false,
    imageAlt: 'Tazón de cereal industrial con leche y prohibición de echar ají gourmet',
    quote: 'Nuestras salsas están formuladas para charcutería fina, mariscos y cortes nobles. Si le echas ají artesanal a hojuelas azucaradas de caja, estás desperdiciando una joya.',
    tags: ['Ultraprocesado', 'Cero Armonía', 'Pecado Culinario'],
    sauceRecommendation: 'ABSTENTE (Guárdalo pal Tomahawk)',
  }
];

export const SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'post-1',
    author: 'Chef Gonzalo Parrilla',
    handle: '@brasas_de_autor',
    location: 'Vitacura, Santiago',
    quote: 'Pusimos BRÍGIDO a prueba en un maridaje de entraña Wagyu y costillar laqueado. El balance entre el ajo chilote asado y el humo nativo juega en las grandes ligas.',
    tag: '#CocinaDeAutor',
    spiceLevel: 'BRÍGIDO',
    rotation: '-rotate-2',
    context: 'Cena degustación y parrilla'
  },
  {
    id: 'post-2',
    author: 'Cami Sommelier & Foodie',
    handle: '@camila_gourmet',
    location: 'Barrio Lastarria, Santiago',
    quote: 'Sopaipillas de zapallo camote con pebre fresco y gotas de PIOLA. El aroma a limón de pica y cilantro de huerta eleva el bocado a una experiencia sensorial increíble.',
    tag: '#MaridajeChileno',
    spiceLevel: 'PIOLA',
    rotation: 'rotate-1',
    context: 'Tapeo & Vinos Chilenos'
  },
  {
    id: 'post-3',
    author: 'Nico Bife & Sanguchería',
    handle: '@nico_bistro',
    location: 'Providencia, Santiago',
    quote: 'Sacamos un sándwich de plateada braseada en brioche con MESTIZO. El toque de miel de ulmo y merkén tostado se convirtió al instante en el plato estrella de la carta.',
    tag: '#AltaSangucheria',
    spiceLevel: 'MESTIZO',
    rotation: '-rotate-1',
    context: 'En la barra del bistró'
  },
  {
    id: 'post-4',
    author: 'Pancho & Vale Gastronomía',
    handle: '@gastronomia_austral',
    location: 'Cerro Concepción, Valparaíso',
    quote: 'Lo probamos junto a un tiradito de corvina y tabla de quesos de oveja madurados. La calidad de la materia prima nacional se nota desde la primera gota.',
    tag: '#GourmetAustral',
    spiceLevel: 'BRÍGIDO',
    rotation: 'rotate-2',
    context: 'Cocina de mar y cordillera'
  }
];

export const RETAILERS: Retailer[] = [
  {
    name: 'Local Oficial en Factoría Franklin',
    category: 'Presencial',
    badge: 'VENTA PRESENCIAL & DEGUSTACIÓN',
    locations: 'Visítanos en nuestro local oficial dentro de Factoría Franklin, el epicentro gastronómico y de oficios artesanales de Santiago. Ven a probar gratis toda nuestra línea en el mesón de cata.',
    address: 'Franklin 741, Barrio Franklin, Santiago (Metro Franklin / Bío Bío)',
    schedule: 'Sábados, Domingos y Festivos de 11:00 a 19:30 hrs',
    availability: 'Las 8 variedades disponibles: Pebre, Cacho, Chileno, Fuego y sin picor (Pime, Chilote, Berenja, Seta), más packs de regalo.',
    highlights: [
      'Degustación en vivo con maridajes de campo',
      'Atención personalizada de los creadores de Ají Veneno',
      'Pago con Tarjeta Débito/Crédito y Transferencia',
      'Retiro inmediato sin costos de envío'
    ],
    actionText: 'VER UBICACIÓN EN MAPA',
    actionUrl: 'https://maps.google.com/?q=Factoria+Franklin+Franklin+741+Santiago',
    iconName: 'Store'
  },
  {
    name: 'Tienda Oficial Mercado Libre',
    category: 'Online',
    badge: 'DESPACHO A TODO CHILE',
    locations: 'Nuestra vitrina online exclusiva para todo el territorio nacional. Compra con la seguridad, respaldo de garantía y velocidad de envíos FULL de Mercado Libre.',
    address: 'Despachos directos desde bodega a tu puerta en 24 a 48 hrs hábiles',
    schedule: 'Tienda digital abierta 24/7 los 365 días del año',
    availability: 'Frascos individuales, Dúos Picantes, Tríos Parrilleros y Pack Completo de 8 Salsas con empaque especial antigolpes.',
    highlights: [
      'Envíos rápidos a todo Chile continental',
      'Compra protegida y garantía Mercado Libre',
      'Hasta 6 o 12 cuotas sin interés según promociones vigentes',
      'Empaque acolchado de máxima seguridad para frascos de vidrio'
    ],
    actionText: 'IR A MERCADO LIBRE',
    actionUrl: 'https://www.mercadolibre.cl',
    iconName: 'ShoppingBag'
  }
];

export const FAQS = [
  {
    q: '¿Dónde puedo comprar Ají Veneno?',
    a: 'Vendemos exclusivamente a través de dos canales oficiales: de manera presencial en nuestro local en Factoría Franklin (Franklin 741, Santiago) donde puedes degustar gratis todas las variedades, y online en nuestra Tienda Oficial de Mercado Libre con envíos protegidos a todo Chile. No comercializamos en supermercados ni tiendas de terceros.'
  },
  {
    q: '¿Pica de verdad o es puro cuento?',
    a: 'Pica de verdad compadre. No es esa agua con vinagre que ponen en frasco de plástico en algunos lados. Acá usamos ají cacho de cabra chileno genuino, ají verde y habanero criollo seleccionados a mano.'
  },
  {
    q: '¿Tiene conservantes químicos raros?',
    a: 'Cero leseras raras. Solo ají natural, vinagres de primera, ajos asados, sal de Cáhuil y humo nativo. Es como si tu abuela campesina hubiera montado una banda de punk rock.'
  },
  {
    q: '¿Dónde se produce?',
    a: '100% en Chile. Los ajíes cacho de cabra vienen de agricultores locales del Valle Central y el sur, ahumados con leña autorizada sustentable.'
  },
  {
    q: '¿Hacen envíos a regiones?',
    a: '¡Claro que sí! Desde Arica hasta Puerto Williams. Empacamos las botellas en cajas reforzadas con stickers y regalitos de la casa.'
  }
];
